### ISSUE TITLE
Can't show filled polygon in Windows client

### ISSUE THREAD

**Issue by qu123xxx** [WorldWideTelescope/sky-banana-party#1]
Hi I'm trying to visualize the same dataset here  in **WWT Windows Client**. However I can't get a color-filled area in **`Sky` frame** by using  **`polygon(RA DEC)`**  string. The result is same as use `Linestring(RA DEC)`.
![image](https://user-images.githubusercontent.com/16397369/81277634-41f85580-9087-11ea-83aa-900377496aac.png)
 **`polygon(RA DEC)`** is available in `sandbox`

**In this app** it is shown like this
![image](https://user-images.githubusercontent.com/16397369/81278334-1d50ad80-9088-11ea-9af4-8cd3cead523c.png)

Is there any way to achieve it？

I have search the code in these two repos find that the render method of polygon is different between windows client and web client whereas latter use some function in webGL SDK.

Thanks in advance for any replies.

**Comment by qu123xxx** [comment]
Well I use `polygon`  achieved some filled area . But the raw data of Gravitational Wave seems have some holes in polygon. Some areas also have parts unfilled. Finally I use `Linestring` instead of polygon. And the `--uside` flag of `ligo-skymap-contour` may help to smooth the line .

**Comment by astrojonathan** [comment]
Winding order may has some effect on this. To fill your vertexes need to be in the correct clockwise or counter clockwise orientation so the normal points toward the camera, otherwise the face is culled.

**Comment by qu123xxx** [comment]
Thanks. I also considered this reason, I will try it when I have time~
